# Generated by Django 5.0 on 2023-12-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('DiscountID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('discount_code', models.IntegerField(default=1)),
                ('discount_percentage', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Car_ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('license_Plate', models.CharField(max_length=10)),
                ('car_Brand', models.CharField(max_length=50)),
                ('car_Type', models.CharField(max_length=50)),
                ('carOwner_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carowner')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('booking_StartDate', models.DateField()),
                ('booking_EndDate', models.DateField()),
                ('total_Cost', models.IntegerField(default=1)),
                ('car_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.customer')),
                ('discount_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField(default=1)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.customer')),
            ],
        ),
    ]
